In [1]:
import numpy as np
import stl
from stl import mesh

# Load STL file and convert to numpy array
stl_mesh = mesh.Mesh.from_file('cube_sample.stl')
vertices = stl_mesh.vectors.reshape(-1, 3)

# Calculate the minimum and maximum x, y, and z coordinates
x_min, y_min, z_min = np.min(vertices, axis=0)
x_max, y_max, z_max = np.max(vertices, axis=0)

# Define the resolution of the height map
resolution = 100

# Generate a grid of x and y values
x = np.linspace(x_min, x_max, resolution)
y = np.linspace(y_min, y_max, resolution)
X, Y = np.meshgrid(x, y)

# Interpolate the z values at each point in the grid
from scipy.interpolate import griddata
Z = griddata(vertices[:, :2], vertices[:, 2], (X, Y), method='linear')

# Smooth the height map
from scipy.ndimage import gaussian_filter
Z_smooth = gaussian_filter(Z, sigma=2)

# Save the height map to a file
np.save('height_map.npy', Z_smooth)

# Load the height map from a file
height_map = np.load('height_map.npy')

print(height_map)

[[20. 20. 20. ... 20. 20. 20.]
 [20. 20. 20. ... 20. 20. 20.]
 [20. 20. 20. ... 20. 20. 20.]
 ...
 [20. 20. 20. ... 20. 20. 20.]
 [20. 20. 20. ... 20. 20. 20.]
 [20. 20. 20. ... 20. 20. 20.]]
